version: "3.6"

services:
  nuthorizr: 
    build: .docker
    restart: on-failure
    volumes:
      - type: bind
        source: ./
        target: /src
    ports:
      - 12345:12345 # lein relp server
